# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rD-TS241JEpZX9_9eKUZRdjtfUHpRSyG
"""

"""
EX 001  Boas-vindas Personalizadas: Crie uma variável para armazenar o nome de
uma pessoa. Peça para o usuário digitar seu nome, armazene-o e depois exiba a
mensagem: "Olá [nome], seja bem-vindo!"
"""
print("===== Boas-vindas Personalizadas: =====\n")
nome = input("Digite o seu nome: ")
print(f"Olá {nome}, seja bem-vindo!\n\n")

"""
EX 002 Endereço Completo: Crie três variáveis: cidade, estado e cep. Peça ao
usuário para preencher cada uma e, ao final, exiba o endereço formatado em
uma única linha.
"""
print("===== Endereço Completo: =====\n")
cidade = input("Digite a sua Cidade: ")
estado = input("Digite o seu Estado: ")
cep = input("Digite o seu Cep: ")
print(f"Você mora em {cidade}, Estado de {estado}, no Cep {cep}\n\n")

"""
EX 003 Soma de Dois Números: Receba dois números inteiros do usuário,
armazeneos em variáveis distintas, calcule a soma e exiba o resultado.
"""
print("===== Soma de Dois Números: =====\n")
n1 = int(input("Digite um valor inteiro: "))
n2 = int(input("Digite outro valor inteiro: "))
print(f"A soma entre {n1} + {n2} = {n1 + n2}\n\n")

"""
EX 004 Calculadora de Idade: Crie uma variável para o ano_nascimento e outra para
o ano_atual. Peça os dados ao usuário, subtraia as variáveis e exiba: "Sua
idade é ou será [resultado] anos".
"""
print("===== Calculadora de Idade: =====\n")
ano_nascimento = int(input("Digite o ano do seu nascimento: "))
ano_atual = int(input("Digite o ano atual: "))
print(f"Sua idade é ou será {ano_atual - ano_nascimento} anos\n\n")

"""
Ex 005 Desafio Calculadora de Gorjeta: * Receba o valor total da conta de um
restaurante. Receba a porcentagem de gorjeta que o cliente deseja deixar (ex:
10, 15 ou 20).
Calcule o valor da gorjeta e o valor total final (conta + gorjeta).
Exiba os dois valores separadamente.
"""
print("===== Desafio Calculadora de Gorjeta: =====\n")
conta = float(input("Digite o valor total da conta: "))
gorjeta = float(input("Digite o percentual que gostaria de ofertar como gorjeta: "))
gorjeta = (gorjeta * conta) / 100
print(f"\nValor final da conta fica em R$:{conta + gorjeta} \nsendo R$:{conta} do consmo no local \ne R$:{gorjeta} de gorjeta ofertada!")

"""
Exercício 1 – Cadastro interativo
Crie um programa que:
• Pergunte o nome do aluno
• Pergunte a idade
• Pergunte se está matriculado (True ou False)
• Mostre tudo organizado na tela
"""
print("===== Cadastro interativo: =====\n")

aluno = input("Digite o nome do Aluno: ")
idade = int(input("Digite a idade do Aluno: "))
matricula = bool(input("O aluno esta matriculado? (True -> Sim), (False -> Não): "))

if matricula:
  print(f"Aluno {aluno}, com idade de {idade} anos, com matricula ativa\n\n")
else:
  print(f"Aluno {aluno}, com idade de {idade} anos, se encontra na fila de espera\n\n")

"""
Exercício 2 – Ano de nascimento
O programa deve:
• Perguntar o nome
• Perguntar o ano de nascimento
• Usar o ano atual como constante
• Calcular e mostrar a idade
"""
print("===== Ano de nascimento: =====\n")

from datetime import date
nome = input("Digite o seu nome: ")
nascimento = int(input("Digite o ano do seu nascimento: "))
ATUAL = date.today().year

print(f"Você tem o terá {ATUAL - nascimento} anos \n\n")

"""
Exercício 3 – Calculadora com input
Peça dois números ao usuário e mostre:
• Soma
• Subtração
• Multiplicação
• Divisão
"""
print("===== Calculadora com input: =====\n")

n1 = float(input("Digite o primeiro número: "))
n2 = float(input("Digite o segundo número: "))

print(f"A soma entre {n1} + {n2} = {n1 + n2}")
print(f"A subtração entre {n1} - {n2} = {n1 - n2}")
print(f"A Multiplicação entre {n1} X {n2} = {n1 * n2}")
print(f"A divisão entre {n1} / {n2} = {n1 / n2} \n\n")

"""
Exercício 4 – Número Par
Peça um número inteiro e verifique se ele é:
• Par
"""
print("===== Número Par: =====\n")

numero = int(input("Digite um número inteiro: "))

if numero % 2 == 0:
  print(f"O número {numero} é par \n\n")
else:
  print(f"O número {numero} é impar \n\n")

"""
Exercício 5 – Divisão inteira explicada
Peça dois números e mostre:
• Divisão inteira
• Resto da divisão
• Explique com comentários no código.
"""
print("===== Divisão inteira explicada: =====\n")

#Entrada dos valores para a realização dos calculos
numero1 = float(input("Digite o primeiro número: "))
numero2 = float(input("Digite o segundo número: "))

#A divisaõ inteira utiliza somente a parte inteira do número (a esquerda da virgula)
print(f"A divisão inteira entre {numero1} e {numero2} = {numero1 // numero2}")

#O resto da disão são as casas decimais apos a virgula (a direita da virgula)
print(f"O resto da divisão entre {numero1} e {numero2} = {numero1 % numero2} \n\n")

"""
Exercício 6 – Maior de idade
Nessa exercício pergunte a idade e mostre se a pessoa é maior de
idade
"""
print("===== Maior idade: =====\n")

idade = int(input("Digite a sua idade: "))

if idade >= 18:
  print(f"Você possui {idade} anos, portanto possui maior idade\n\n")
else:
  print(f"Você possui {idade} anos, portanto possui menor idade\n\n")

"""
Exercício 7 – Média do aluno
Peça:
• Duas notas
• Calcule a média e diga se o aluno está aprovado (média ≥ 7).
"""
print("===== Média d aluno: =====\n")

nota1 = float(input("Digite a primeira nota obtida: "))
nota2 = float(input("Digite a segunda nota obtida: "))
media = (nota1 + nota2) / 2

if media >= 7:
  print(f"Parabens, você atingiu o criterio minimo de média 7, portanto foi aprovado com nota {media}\n\n")
else:
  print(f"Infelismente você não atingiu o critério minimo de nota 7, portanto esta de recuperação por ter obtido nota {media}\n\n")

"""
Exercício 8 – Acesso ao sistema
Pergunte ao usuário:
• Se está logado
• Se é administrador
• Verifique se ele pode acessar o sistema.
"""
print("===== Acesso ao sistema: =====\n")

login = input("Você está logado no sistema? (sim / não): ")
admin = input("Você possui nivel administrador? (sim / não): ")

if login == "sim" or login == "Sim" or login == "SIM":
  if admin == "sim" or admin == "Sim" or admin == "SIM":
    print("Acesso concediddo com sucesso!!\n\n")
else:
  print("Acesso negado, por hierarquia de nivel ou falta de login\n\n")

"""
Exercício 10 – Desafio final
Crie um programa que:
• Pergunte:
• Nome do aluno
• Idade
• Três notas
• Calcule a média
• Verifique:
• Se é maior de idade
• Se a média é par ou ímpar
• Se está aprovado (média ≥ 7)
• Mostre tudo organizado na tela
"""
print("===== Desafio Final: =====/n")

nome_aluno = input("Digite o nome do aluno: ")
idade = int(input("Digite a idade: "))
nota1 = float(input("Informe a primeira nota obtida: "))
nota2 = float(input("Informe a segunda nota obtida: "))
nota3 = float(input("Informe a terceira nota obtida: "))
media = (nota1 + nota2 + nota3) / 3

print("\n_______ Processando... ... ... \n")

if idade >= 18:
  print(f"O aluno(a) {nome_aluno} ja possui a maior idade")
else:
  print(f"O aluno(a) {nome_aluno} Não possui a maio idade")

if media % 2 == 0:
  print(f"A média final do aluno(a) {nome_aluno} é par")
else:
  print(f"A média final do aluno(a) {nome_aluno} é impar")

if media >= 7:
  print(f"Parabens {nome_aluno} você foi aprovado com nota {media}")
else:
  print(f"Não foi desta vez {nome_aluno}, você obteve média final de {media} e a nossa tolerancia é de 7.00, portanto esta de recuperação")

"""
1. Crie um programa que tenha uma função que:
Receba dois números
Retorne o maior deles.
"""
def maior_numero(numero_1, numero_2):
  if numero_1 > numero_2 :
    return numero_1
  elif numero_2 > numero_1 :
    return numero_2
  else:
    return print("\nOs valores são identicos!\n")

print("===== Maior Número ===== \n")

n1 = float(input("Digite o primeiro valor: "))
n2 = float(input("Digite o segundo valor: "))

if n1 != n2:
  print(f"\nO Maior número é {maior_numero(n1, n2)}\n")
else:
  maior_numero(n1, n2)

"""
2. Crie um programa, cuja função:
Receba um valor em Reais
Retorne o valor com 15% de imposto.
"""
def imposto (valor):
  valor = valor * 1.15
  return valor

print("===== Calculadora de Imposto: =====\n")

reais = float(input("Digite o valor a ser declarado: "))

print(f"Com o valor de R:{reais:.2f} + o imposto passara a a ser R$:{imposto(reais):.2f}\n")

"""
3. Crie um programa que tenha:
Uma função para calcular o IMC
Uma função para classificar o IMC
Usar as duas funções e retornar ao usuário tanto o valor de IMC e a
categoria.
"""
def calculo_imc(peso, altura):
    imc = peso / (altura ** 2)
    return imc

def classificacao_imc(imc):
    if imc < 18.5:
        return "Classificação: Baixo peso, Risco de doenças: Alto"
    elif 18.5 <= imc <= 24.9:
        return "Classificação: Peso Normal, Risco de doenças: Baixo"
    elif 25 <= imc <= 29.9:
        return "Classificação: Sobrepeso, Risco de doenças: Moderado"
    elif 30 <= imc <= 34.9:
        return "Classificação: Obesidade Grau I, Risco de doenças: Alto"
    elif 35 <= imc <= 39.9:
        return "Classificação: Obesidade Grau II, Risco de doenças: Muito Alto"
    else:
        return "Classificação: Obesidade Grau III, Risco de doenças: Extremamente Alto"

print("===== Calculo e classifiação de IMC: =====\n")

peso = float(input("Digite o seu peso (kg): "))
altura = float(input("Digite a sua altura (m): "))

imc = calculo_imc(peso, altura)
classificacao = classificacao_imc(imc)

print(f"O seu índice de massa corporal é {imc:.2f}, portanto a sua {classificacao}.")