# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rD-TS241JEpZX9_9eKUZRdjtfUHpRSyG
"""

"""
EX 001  Boas-vindas Personalizadas: Crie uma variável para armazenar o nome de
uma pessoa. Peça para o usuário digitar seu nome, armazene-o e depois exiba a
mensagem: "Olá [nome], seja bem-vindo!"
"""
print("===== Boas-vindas Personalizadas: =====\n")
nome = input("Digite o seu nome: ")
print(f"Olá {nome}, seja bem-vindo!\n\n")

"""
EX 002 Endereço Completo: Crie três variáveis: cidade, estado e cep. Peça ao
usuário para preencher cada uma e, ao final, exiba o endereço formatado em
uma única linha.
"""
print("===== Endereço Completo: =====\n")
cidade = input("Digite a sua Cidade: ")
estado = input("Digite o seu Estado: ")
cep = input("Digite o seu Cep: ")
print(f"Você mora em {cidade}, Estado de {estado}, no Cep {cep}\n\n")

"""
EX 003 Soma de Dois Números: Receba dois números inteiros do usuário,
armazeneos em variáveis distintas, calcule a soma e exiba o resultado.
"""
print("===== Soma de Dois Números: =====\n")
n1 = int(input("Digite um valor inteiro: "))
n2 = int(input("Digite outro valor inteiro: "))
print(f"A soma entre {n1} + {n2} = {n1 + n2}\n\n")

"""
EX 004 Calculadora de Idade: Crie uma variável para o ano_nascimento e outra para
o ano_atual. Peça os dados ao usuário, subtraia as variáveis e exiba: "Sua
idade é ou será [resultado] anos".
"""
print("===== Calculadora de Idade: =====\n")
ano_nascimento = int(input("Digite o ano do seu nascimento: "))
ano_atual = int(input("Digite o ano atual: "))
print(f"Sua idade é ou será {ano_atual - ano_nascimento} anos\n\n")

"""
Ex 005 Desafio Calculadora de Gorjeta: * Receba o valor total da conta de um
restaurante. Receba a porcentagem de gorjeta que o cliente deseja deixar (ex:
10, 15 ou 20).
Calcule o valor da gorjeta e o valor total final (conta + gorjeta).
Exiba os dois valores separadamente.
"""
print("===== Desafio Calculadora de Gorjeta: =====\n")
conta = float(input("Digite o valor total da conta: "))
gorjeta = float(input("Digite o percentual que gostaria de ofertar como gorjeta: "))
gorjeta = (gorjeta * conta) / 100
print(f"\nValor final da conta fica em R$:{conta + gorjeta} \nsendo R$:{conta} do consmo no local \ne R$:{gorjeta} de gorjeta ofertada!")